name: Run .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./MyProject/MyProject.csproj

    - name: Build project
      run: dotnet build ./MyProject/MyProject.csproj --no-restore

    - name: Run project
      run: dotnet run --project ./MyProject/MyProject.csproj
